# Generated by Django 5.0 on 2026-02-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_template_file_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='templatefile',
            new_name='template_fi_tenant__925725_idx',
            old_name='tmpl_tenant_updated_idx',
        ),
    ]
