# Generated by Django 5.0 on 2026-02-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_rename_tmpl_tenant_updated_idx_template_fi_tenant__925725_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='templatefile',
            new_name='tmpl_tenant_updated_idx',
            old_name='template_fi_tenant__925725_idx',
        ),
    ]
