# Generated by Django 5.0 on 2026-02-12

import django.contrib.postgres.indexes
from django.db import migrations

from pgvector.django import VectorField


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_searchanalyticsmodel_searchindexmodel_indexed_at_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name="searchindexmodel",
            name="embedding",
            field=VectorField(blank=True, dimensions=1024, null=True),
        ),

        migrations.AddIndex(
            model_name="searchindexmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="search_title_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
