# Generated by Django 5.0 on 2026-02-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_pgvector_and_trigram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindexmodel',
            name='entity_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('clause', 'Clause'), ('template', 'Template'), ('workflow', 'Workflow'), ('document', 'Document'), ('approval', 'Approval'), ('audit_log', 'Audit Log')], max_length=50),
        ),
    ]
