# Generated by Django 5.0 on 2026-01-17 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClauseAnchor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("example_text", models.TextField()),
                ("embedding", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_clause_anchors",
                "ordering": ["category", "label"],
                "indexes": [
                    models.Index(
                        fields=["label", "is_active"],
                        name="ai_clause_a_label_d1fd4d_idx",
                    ),
                    models.Index(
                        fields=["category"], name="ai_clause_a_categor_529d7d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DraftGenerationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "task_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("contract_type", models.CharField(max_length=100)),
                ("template_id", models.UUIDField(blank=True, null=True)),
                ("input_params", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("generated_text", models.TextField(blank=True)),
                ("citations", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_draft_generation_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="ai_draft_ge_tenant__e1a944_idx",
                    ),
                    models.Index(
                        fields=["task_id"], name="ai_draft_ge_task_id_6e0eac_idx"
                    ),
                ],
            },
        ),
    ]
